name = "hono-github-oauth-demo"
compatibility_date = "2024-08-13"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "STORE_KV"
id = "fb8cd148f0314d18b5d9ffee41dc2c4f"
preview_id = "fb8cd148f0314d18b5d9ffee41dc2c4f"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
